title: Ingest Travel Guide
description: Documentation for developers new to the HCA DPC Ingest component

# Dependencies
markdown:       kramdown
highlighter:    rouge

# Permalinks
permalink:      pretty

theme: jekyll-theme-primer

plugins:
  - jekyll-font-awesome
  - jekyll-mermaid

mermaid:
  src: '/js/mermai.min.js'
  src_config: '/js/mermaid_config.js'