# Dependencies
markdown:       kramdown
highlighter:    rouge

# Permalinks
permalink:      pretty

theme: jekyll-theme-slate
title: Ingest Travel Guide
description: Documentation for developers new to the HCA DPC Ingest component
